# Generated by Django 5.2.7 on 2025-10-19 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT/RUN')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('pueblo_originario', models.BooleanField(default=False)),
                ('discapacidad', models.BooleanField(default=False)),
                ('privada_libertad', models.BooleanField(default=False)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True)),
                ('controles_prenatales', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_parto', models.DateField()),
                ('tipo_parto', models.CharField(choices=[('vaginal', 'Vaginal'), ('instrumental', 'Instrumental'), ('cesarea_electiva', 'Cesárea electiva'), ('cesarea_urgencia', 'Cesárea urgencia'), ('domicilio', 'Domicilio'), ('prehospitalario', 'Prehospitalario')], max_length=20)),
                ('inicio_parto', models.CharField(choices=[('espontaneo', 'Espontáneo'), ('inducido', 'Inducido')], max_length=12)),
                ('analgesia', models.CharField(blank=True, choices=[('neuroaxial', 'Neuroaxial'), ('endovenosa', 'Endovenosa'), ('oxido_nitroso', 'Óxido nitroso'), ('general', 'General'), ('local', 'Local'), ('no_farmacologica', 'No farmacológica')], max_length=20, null=True)),
                ('acompanamiento', models.CharField(choices=[('ninguno', 'Ninguno'), ('trabajo_parto', 'Trabajo de parto'), ('expulsivo', 'Expulsivo')], default='ninguno', max_length=20)),
                ('episiotomia', models.BooleanField(default=False)),
                ('oxitocina', models.BooleanField(default=False)),
                ('plan_parto', models.BooleanField(default=False)),
                ('contacto_piel_piel', models.BooleanField(default=False)),
                ('alojamiento_conjunto', models.BooleanField(default=False)),
                ('cesarea_programada', models.BooleanField(default=False)),
                ('edad_gestacional', models.PositiveIntegerField(help_text='Semanas')),
                ('complicaciones', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partos', to='gestacion.madre')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemorragia_postparto', models.BooleanField(default=False)),
                ('preeclampsia_eclampsia', models.BooleanField(default=False)),
                ('sepsis', models.BooleanField(default=False)),
                ('otras_complicaciones', models.TextField(blank=True, null=True)),
                ('transfusion_sanguinea', models.BooleanField(default=False)),
                ('histerectomia', models.BooleanField(default=False)),
                ('traslado_uci', models.BooleanField(default=False)),
                ('parto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complicacion', to='gestacion.parto')),
            ],
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario')], max_length=2)),
                ('peso_nacer', models.DecimalField(decimal_places=1, help_text='gramos (ej: 3200.0)', max_digits=5)),
                ('apgar_1', models.PositiveIntegerField()),
                ('apgar_5', models.PositiveIntegerField()),
                ('anomalias_congenitas', models.BooleanField(default=False)),
                ('profilaxis_hepatitisb', models.BooleanField(default=False)),
                ('profilaxis_ocular', models.BooleanField(default=False)),
                ('reanimacion', models.CharField(choices=[('ninguna', 'Ninguna'), ('basica', 'Básica'), ('avanzada', 'Avanzada')], default='ninguna', max_length=10)),
                ('asfixia_neonatal', models.BooleanField(default=False)),
                ('tamizaje_metabolico', models.BooleanField(default=False)),
                ('tamizaje_auditivo', models.BooleanField(default=False)),
                ('tamizaje_cardiaco', models.BooleanField(default=False)),
                ('fallecido', models.BooleanField(default=False)),
                ('tipo_fallecimiento', models.CharField(blank=True, choices=[('aborto', 'Aborto'), ('mortinato', 'Mortinato'), ('mortineonato', 'Mortineonato')], max_length=20, null=True)),
                ('metodo_alimentacion', models.CharField(blank=True, choices=[('LME', 'LME'), ('mixta', 'Mixta'), ('formula', 'Fórmula'), ('no_amamantado', 'No amamantado'), ('HTLV_VIH', 'HTLV/VIH'), ('Ley21155', 'Ley 21.155')], max_length=15, null=True)),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rns', to='gestacion.parto')),
            ],
        ),
    ]
